[package]
name = "cooltest"
version = "0.1.2"
edition = "2021"



[dependencies]
rand="0.8"
rayon="1.7"
clap = { version = "4.3", features = ["derive"] }
itertools="0.11"
pyo3={ version = "0.19", features = ["auto-initialize"] }
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
