name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Rust
      uses: dtolnay/rust-toolchain@master
      with:
          toolchain: stable
          components: rustfmt, clippy

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-varsion: '3.x'
    
    - name: Install SciPy
      run: python -m pip install scipy

    - name: Build
      run: cargo build --verbose
    - name: Build with scipy
      run: cargo build --verbose --features scipy
    - name: Run tests
      run: cargo test --verbose
    - name: Run tests with scipy
      run: cargo test --verbose --features scipy
    - name: Format
      run: cargo fmt --all -- --check
    - name: Clippy
      run: cargo clippy -- -D warnings
    
